# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Frontend – Build & Deploy to Cloudways

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_ROOT: /home/1475017.cloudwaysapps.com/ascqrnhbfh/public_html
      DEST: /home/1475017.cloudwaysapps.com/ascqrnhbfh/public_html/public

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Build frontend
        working-directory: frontend
        run: |
          set -euo pipefail
          npm ci
          npm run build
          test -d dist || (echo "❌ Build nije kreirao dist/"; exit 1)

      # 1) (Opcionalno, ali preporučeno) Očisti stare assete preko SSH (MASTER)
      - name: Load master SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MASTER_SSH_KEY }}

      - name: Trust master host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.MASTER_SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Clean old assets on server (via SSH)
        run: |
          ssh "${{ secrets.MASTER_SSH_USER }}"@"${{ secrets.MASTER_SSH_HOST }}" \
            "rm -rf '${{ env.DEST }}'/assets/* || true"

      # 2) Deploy preko SFTP kao APP user (SFTP-only)
      - name: Deploy dist via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server:     ${{ secrets.SFTP_HOST }}
          username:   ${{ secrets.SFTP_USER }}
          password:   ${{ secrets.SFTP_PASS }}
          port:       22
          sftp_only:  true
          # pošalji SVE iz dist/
          local_path:  'frontend/dist/*'
          # VAŽNO: path relativan za SFTP root (bez /home/...)
          remote_path: 'public_html/public/'

      # 3) Laravel cache clear (MASTER SSH)
      - name: Clear Laravel caches
        run: |
          ssh "${{ secrets.MASTER_SSH_USER }}"@"${{ secrets.MASTER_SSH_HOST }}" \
            "cd '${{ env.APP_ROOT }}' && php artisan optimize:clear || true"

      - name: Sanity check public/
        run: |
          ssh "${{ secrets.MASTER_SSH_USER }}"@"${{ secrets.MASTER_SSH_HOST }}" \
            "echo '== listing $DEST =='; ls -la '${{ env.DEST }}' | head -n 100 && echo 'Deploy OK ✅'"
