name: Frontend – Build & Deploy to Cloudways

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      DEST: /home/1475017.cloudwaysapps.com/ascqrnhbfh/public_html/public

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install & Build (frontend)
        working-directory: frontend
        run: |
          set -euo pipefail
          npm ci
          npm run build

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Trust Cloudways host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Deploy frontend to Cloudways
        run: |
          set -euo pipefail

          APP_ROOT="/home/1475017.cloudwaysapps.com/ascqrnhbfh/public_html"
          DEST="$APP_ROOT/public"

          echo "== Ensure remote dirs exist =="
          ssh "$SSH_USER@$SSH_HOST" "mkdir -p \"$DEST/assets\""

          echo "== Clean old assets =="
          ssh "$SSH_USER@$SSH_HOST" "rm -rf \"$DEST/assets\"/* || true"

          echo "== Upload new build =="
          if [ -d "frontend/dist/assets" ]; then
            scp -r frontend/dist/assets/. "$SSH_USER@$SSH_HOST:$DEST/assets/"
          else
            echo "⚠️ No local assets found in frontend/dist/assets"
          fi

          echo "== Upload index.html =="
          scp frontend/dist/index.html "$SSH_USER@$SSH_HOST:$DEST/index.html"

      - name: Clear Laravel caches
        run: |
          ssh "$SSH_USER@$SSH_HOST" \
            'cd /home/1475017.cloudwaysapps.com/ascqrnhbfh/public_html && php artisan optimize:clear || true'

      - name: Sanity check remote path
        run: |
          ssh "$SSH_USER@$SSH_HOST" \
            'echo "== User info =="; whoami; pwd; echo "== Files =="; ls -l /home/1475017.cloudwaysapps.com/ascqrnhbfh/public_html/public'
