# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Frontend – Build & Deploy to Cloudways

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_ROOT: /home/1475017.cloudwaysapps.com/ascqrnhbfh/public_html
      DEST: /home/1475017.cloudwaysapps.com/ascqrnhbfh/public_html/public

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Build frontend
        working-directory: frontend
        run: |
          set -euo pipefail
          npm ci
          npm run build
          test -d dist || (echo "❌ Build nije kreirao dist/"; exit 1)

      # === DEPLOY (SFTP kao APP USER) ===
      - name: Deploy dist via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.SFTP_HOST }}         # 64.226.68.160
          username: ${{ secrets.SFTP_USER }}       # expressajt
          password: ${{ secrets.SFTP_PASS }}       # lozinka iz Application Credentials
          protocol: sftp
          port: 22
          local-dir: frontend/dist/
          server-dir: public_html/public/          # relativno od SFTP root-a
          dangerous-clean-slate: true
          exclude: |
            index.php
            storage
            .htaccess
          log-level: verbose

      # === ARTISAN (SSH kao MASTER USER) – opciono ===
      - name: Load master SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MASTER_SSH_KEY }}

      - name: Trust master host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.MASTER_SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Clear Laravel caches
        run: |
          ssh "${{ secrets.MASTER_SSH_USER }}"@"${{ secrets.MASTER_SSH_HOST }}" \
            "cd '${{ env.APP_ROOT }}' && php artisan optimize:clear || true"

      - name: Sanity check public/
        run: |
          ssh "${{ secrets.MASTER_SSH_USER }}"@"${{ secrets.MASTER_SSH_HOST }}" \
            "echo '== listing $DEST =='; ls -la '${{ env.DEST }}' | head -n 100 && echo 'Deploy OK ✅'"
